## Flyway for DEV
#spring.flyway.locations=classpath:/dev/db/migration
#
## Logging overrides for DEV
#logging.level.root=INFO
#logging.level.com.example.demo=DEBUG
#logging.level.org.hibernate.SQL=DEBUG
#logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
#logging.level.com.zaxxer.hikari=DEBUG