# Flyway for STAGING
spring.flyway.locations=classpath:/stg/db/migration

# Logging overrides for STAGING
logging.level.root=INFO
logging.level.com.example.demo=INFO
logging.level.org.hibernate.SQL=INFO
logging.level.com.zaxxer.hikari=INFO