## Flyway (PROD)
#spring.flyway.locations=classpath:/prod/db/migration
#
## Logging (minimal)
#logging.level.root=INFO
#logging.level.com.example.demo=INFO
#logging.level.org.hibernate.SQL=WARN
#logging.level.com.zaxxer.hikari=WARN