# Flyway for DEV
spring.flyway.locations=classpath:/dev/db/migration

# Logging overrides for DEV
logging.level.root=INFO
logging.level.com.example.demo=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
logging.level.com.zaxxer.hikari=DEBUG

app.oauth2.redirect-uri=https://api.dev.winestore.id.vn/oauth2/redirect
# Google OAuth2 Configuration
spring.security.oauth2.client.registration.google.client-id=${CLIENT_GOOGLE_ID}
spring.security.oauth2.client.registration.google.client-secret=${CLIENT_GOOGLE_CODE}
spring.security.oauth2.client.registration.google.scope=${CLIENT_GOOGLE_SCOPE}
spring.security.oauth2.client.registration.google.redirect-uri=https://api.dev.winestore.id.vn/login/oauth2/code/google
server.forward-headers-strategy=framework
logging.level.org.springframework.security=DEBUG

# SpringDoc OpenAPI Configuration
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.api-docs.path=/v3/api-docs

# Swagger UI Configuration
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha
springdoc.swagger-ui.tryItOutEnabled=true
springdoc.swagger-ui.displayRequestDuration=true
springdoc.swagger-ui.filter=true

# AI Endpoint
app.ai.endpoint=${AI_API_BASE_URL}


momo.returnUrl=https://www.dev.winestore.id.vn/profile/orders
momo.ipnUrl=https://api.dev.winestore.id.vn/api/v1/payment/momo-ipn